build:
  - apt-get update
  - apt-get install -y software-properties-common
  - apt-get install -y python-software-properties python g++ make
  - apt-add-repository ppa:chris-lea/node.js
  - apt-get update
  - apt-get install -y nodejs
  - npm install -g grunt-cli
  - composer install --no-interaction --ansi --no-progress
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:update --force
  - npm install
  - php app/console doctrine:fixtures:load --fixtures=src/Afup/BarometreBundle/DataTest/ORM/ -n
  - grunt
