files:
  ignore:
    - 'src/Afup/BarometreBundle/Resources/assets/sass/vendor/**'
    - 'src/Afup/BarometreBundle/Resources/assets/sass/generated/**'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 1
  brace-style:
    - 1
    - allow-single-line: true
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format:
    - 1
    - convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
  mixins-before-declarations: 1
  no-color-keywords: 1
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-trailing-zero: 1
  no-url-protocols: 1
  placeholder-in-extend: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - ignore-custom-properties: false
  quotes:
    - 1
    - style: double
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-colon:
    - 1
    - include: true
  space-after-comma: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 1
    - convention: hyphenatedlowercase
  zero-unit: 1
